[package]
name = "sort_json"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
jsonxf = "1.1"
walkdir = "2.3"
